### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Drzaln** [falihnaufal17/REST-API-GoLang#1]
Where is the README files?
I can't try it by myself

**Comment by falihnaufal17** [comment]
Wait, it's still developing and there are many bug

falih

Pada tanggal Min, 22 Sep 2019 18.11, Doddy Rizal Novianto <
notifications@github.com> menulis:

**Comment by Drzaln** [comment]
Okay, keep it up :fire:

**Comment by falihnaufal17** [comment]
Readme done!
Happy coding!😊

falih

Pada tanggal Min, 22 Sep 2019 19.07, Doddy Rizal Novianto <
notifications@github.com> menulis:
